CREATE TABLE Match2011 (
	tourney_id varchar(300) ,
	tourney_name varchar(300) ,
	surface varchar(300) ,
	draw_size int ,
	tourney_level varchar(300) ,
	tourney_date varchar(300) ,
	match_num varchar(300) ,
	winner_id varchar(300) ,
	winner_seed int,
	winner_entry varchar(300),
	winner_name varchar(300) ,
	winner_hand varchar(300) ,
	winner_ht int ,
	winner_ioc varchar(300) ,
	winner_age float ,
	winner_rank int ,
	winner_rank_points int ,
	loser_id varchar(300) ,
	loser_seed int,
	loser_entry varchar(300),
	loser_name varchar(300) ,
	loser_hand varchar(300) ,
	loser_ht int ,
	loser_ioc varchar(300) ,
	loser_age float  ,
	loser_rank int ,
	loser_rank_points int ,
	score varchar(300) ,
	best_of int ,
	round varchar(300) ,
	minutes int ,
	w_ace int ,
	w_df int ,
	w_svpt int ,
	w_1stIn int ,
	w_1stWon int ,
	w_2ndWon int ,
	w_SvGms int ,
	w_bpSaved int ,
	w_bpFaced int ,
	l_ace int ,
	l_df int ,
	l_svpt int ,
	l_1stIn int ,
	l_1stWon int ,
	l_2ndWon int ,
	l_SvGms int ,
	l_bpSaved int ,
	l_bpFaced int 
);

