CREATE TABLE Match2001 (
	tourney_id varchar(10) NOT NULL,
	tourney_name varchar(20) NOT NULL,
	surface varchar(20) NOT NULL,
	draw_size int NOT NULL,
	tourney_level varchar(10) NOT NULL,
	tourney_date varchar(10) NOT NULL,
	match_num varchar(10) NOT NULL,
	winner_id varchar(10) NOT NULL,
	winner_seed int,
	winner_entry varchar(10),
	winner_name varchar(20) NOT NULL,
	winner_hand varchar(1) NOT NULL,
	winner_ht int NOT NULL,
	winner_ioc varchar(3) NOT NULL,
	winner_age float NOT NULL,
	winner_rank int NOT NULL,
	winner_rank_points int NOT NULL,
	loser_id varchar(10) NOT NULL,
	loser_seed int,
	loser_entry varchar(10),
	loser_name varchar(20) NOT NULL,
	loser_hand varchar(1) NOT NULL,
	loser_ht int NOT NULL,
	loser_ioc varchar(3) NOT NULL,
	loser_age float NOT NULL ,
	loser_rank int NOT NULL,
	loser_rank_points int NOT NULL,
	score varchar(20) NOT NULL,
	best_of int NOT NULL,
	round varchar(10) NOT NULL,
	minutes int NOT NULL,
	w_ace int NOT NULL,
	w_df int NOT NULL,
	w_svpt int NOT NULL,
	w_1stIn int NOT NULL,
	w_1stWon int NOT NULL,
	w_2ndWon int NOT NULL,
	w_SvGms int NOT NULL,
	w_bpSaved int NOT NULL,
	w_bpFaced int NOT NULL,
	l_ace int NOT NULL,
	l_df int NOT NULL,
	l_svpt int NOT NULL,
	l_1stIn int NOT NULL,
	l_1stWon int NOT NULL,
	l_2ndWon int NOT NULL,
	l_SvGms int NOT NULL,
	l_bpSaved int NOT NULL,
	l_bpFaced int NOT NULL
);

